apiVersion: batch/v1
kind: Job
metadata:
  name: peach-java
  labels:
    jobgroup: peach-java
spec:
  backoffLimit: 0
  template:
    metadata:
      name: peach-java
      labels:
        jobgroup: peach-java
    spec:
      containers:
      - name: peach-java
        image: maven:3.5.3-jdk-8
        env:
        - name: PROJECT
          value: "$PROJECT"
        command: ["sh", "-c"]
        args:
        - echo $(PROJECT)
      restartPolicy: Never
