apiVersion: batch/v1
kind: Job
metadata:
  name: peach-java-%PROJECT-NAME%
  labels:
    jobgroup: peach-java
spec:
  backoffLimit: 0
  template:
    metadata:
      name: peach-java
      labels:
        jobgroup: peach-java
    spec:
      containers:
      - name: peach-java
        image: maven:3.5.3-jdk-8
        volumeMounts:
        - mountPath: /peachee-java-flat
          name: peachee-java-flat
        env:
        - name: PROJECT
          value: "%PROJECT%"
        - name: SONAR_OPTS
          valueFrom:
            secretKeyRef:
              name: sonar
              key: opts
        - name: GCLOUD_STORAGE_TOKEN # gcloud auth print-access-token
          valueFrom:
            secretKeyRef:
              name: gcloud-storage
              key: token
        command: ["sh", "-c"]
        args:
        - "/peachee-java-flat/peachee-java-flat/$(PROJECT)/checkout.sh &&
           cd /project &&
           mkdir /dump &&
           mvn clean package org.sonarsource.scanner.maven:sonar-maven-plugin:LATEST:sonar -B -e -DskipTests -Dsonar.projectKey=\"%PROJECT%\" -Dsonar.projectName=\"%PROJECT%\" $SONAR_OPTS &&
           export dump_file=dump-$PROJECT.tar.gz &&
           tar cjf $dump_file /dump &&
           curl --upload-file $dump_file -H \"Authorization: Bearer $GCLOUD_STORAGE_TOKEN\" \"https://storage.googleapis.com/scientists/issues/$dump_file\"
          "
        resources:
          requests:
            cpu: 0.51
      volumes:
      - name: peachee-java-flat
        gitRepo:
          repository: "https://github.com/dbolkensteyn/peachee-java-flat.git"
      restartPolicy: Never
