apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: sonarqube-deployment
  labels:
    app: sonarqube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarqube
  template:
    metadata:
      labels:
        app: sonarqube
    spec:
      containers:
      - name: sonarqube
        image: sonarqube:6.7
        ports:
        - containerPort: 9000
        env:
        - name: SONARQUBE_JDBC_USERNAME
          valueFrom:
            secretKeyRef:
              name: sonarqube-jdbc
              key: user
        - name: SONARQUBE_JDBC_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sonarqube-jdbc
              key: pass
        - name: SONARQUBE_JDBC_URL
          valueFrom:
            secretKeyRef:
              name: sonarqube-jdbc
              key: url
        - name: GITHUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: github
              key: token
        command: ["sh", "-c"]
        args:
        - "echo sonar.log.level=TRACE >> $SONARQUBE_HOME/conf/sonar.properties &&
           curl -L -H \"Accept: application/octet-stream\" \"https://$GITHUB_TOKEN:@api.github.com/repos/SonarSource/sonar-security/releases/assets/6584635\" -o $SONARQUBE_HOME/extensions/plugins/sonarsecurity.jar &&
           curl -s -L https://sonarsource.bintray.com/Distribution/sonar-java-plugin/sonar-java-plugin-5.2.0.13398.jar -o $SONARQUBE_HOME/extensions/plugins/sonarjava.jar &&
           $SONARQUBE_HOME/bin/run.sh"
        resources:
          requests:
            cpu: 0.51
            memory: "2G"
        readinessProbe:
          exec:
            command: ["sh", "-c", "curl -s http://localhost:9000/api/system/status | grep \\\"status\\\":\\\"UP\\\""]
          initialDelaySeconds: 30
          periodSeconds: 5
---
kind: Service
apiVersion: v1
metadata:
  name: sonarqube-service
spec:
  type: LoadBalancer
  selector:
    app: sonarqube
  ports:
  - protocol: TCP
    port: 9000
